# Generated by Django 4.1.7 on 2023-04-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField(unique=True, verbose_name="Класс")),
                (
                    "max_capacity",
                    models.IntegerField(verbose_name="Максимальное вместимость"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("decimail", models.IntegerField(verbose_name="Стоимость(UZS)")),
                ("image1", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("image2", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("image3", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                (
                    "image4",
                    models.ImageField(
                        blank=True, default=None, upload_to="photos/%Y/%m/%d/"
                    ),
                ),
                ("amount_rooms", models.IntegerField(verbose_name="Количество комнат")),
            ],
            options={
                "verbose_name": "Добавление комнаты",
                "verbose_name_plural": "Добавление комнаты",
            },
        ),
        migrations.CreateModel(
            name="BookingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("surname", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "email",
                    models.CharField(max_length=50, unique=True, verbose_name="Почта"),
                ),
                (
                    "telephone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Телефон номер"
                    ),
                ),
                (
                    "commentary",
                    models.TextField(blank=True, verbose_name="Комментария"),
                ),
                ("date_in", models.DateField(verbose_name="Дата входа")),
                ("date_out", models.DateField(verbose_name="Дата выхода")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "book_room",
                    models.ForeignKey(
                        max_length=30,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rooms_app.room",
                        verbose_name="Заброн. комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированная комната",
                "verbose_name_plural": "Забронированные комнаты",
                "ordering": ["time_create", "name"],
            },
        ),
    ]
